import user from './assets/user.png'
export const ClassList=[
{
	Name:'Management des systémes d informtion',
	startdate:'8:00',
	enddate:'10:00',
	period:['AM','PM'],
	filiere:'Genie Logiciel-Groupe 2',
	member:35,
	memberList:[
      {
      	username:'',
      	image:'./assets/user.png'
      },      {
            username:'',
            image:'http://localhost:3000/Doc/logo03.png'
      },
      {
      	username:'',
      	image:'http://localhost:3000/Doc/logo03.png'
      },
      {
      	username:'',
      	image:'http://localhost:3000/Doc/logo03.png'
      },
      {
      	username:'',
      	image:'http://localhost:3000/Doc/logo03.png'
      },
      {
      	username:'',
      	image:'http://localhost:3000/Doc/logo03.png'
      },
      {
      	username:'',
      	image:'http://localhost:3000/Doc/logo03.png'
      }
	]
},{
      Name:'Management des systémes d informtion',
      startdate:'8:00',
      enddate:'10:00',
      period:['AM','PM'],
      filiere:'Genie Logiciel-Groupe 2',
      member:35,
      memberList:[
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      }
      ]
},
{
      Name:'Management des systémes d informtion',
      startdate:'8:00',
      enddate:'10:00',
      period:['AM','PM'],
      filiere:'Genie Logiciel-Groupe 2',
      member:35,
      memberList:[
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      }
      ]
},{
      Name:'Management des systémes d informtion',
      startdate:'8:00',
      enddate:'10:00',
      period:['AM','PM'],
      filiere:'Genie Logiciel-Groupe 2',
      member:35,
      memberList:[
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      }
      ]
},{
      Name:'Management des systémes d informtion',
      startdate:'8:00',
      enddate:'10:00',
      period:['AM','PM'],
      filiere:'Genie Logiciel-Groupe 2',
      member:35,
      memberList:[
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      }
      ]
},{
      Name:'Management des systémes d informtion',
      startdate:'8:00',
      enddate:'10:00',
      period:['AM','PM'],
      filiere:'Genie Logiciel-Groupe 2',
      memberList:[
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      },
      {
            username:'',
            image:'./assets/user.png'
      }
      ]
},
]